### PR TITLE
Add mod.conf

### PR DESCRIPTION
**Pull request by taikedz**
This way the folder can be named whatever - keep `-master`, be named "Eyjafjallajokull", etc - but the mod will still be recognized and loaded as `chat_c`

### CODE REVIEW

**Comment by wilkgr76** [comment]
Is that something new? Last I checked MT doesn't like folder names with "-". Let me try this.

**Comment by wilkgr76** [comment]
Woah!! This is _awesome_! Thanks @taikedz!

**Comment by taikedz** [comment]
yup. been there at least since 0.4.13 I think.... or even before...

**Comment by wilkgr76** [comment]
Oh wow. I totally missed that. Thanks @taikedz =)

**Pull request merged**
